# Generated by Django 4.1.3 on 2023-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(
                help_text="Select a language for this book", to="catalog.language"
            ),
        ),
    ]
